auxiliarry.o: auxiliarry.cpp auxiliarry.h
	g++ -std=c++11 -ggdb3 -c auxiliarry.cpp -lpthread

circularBuffer.o: circularBuffer.cpp circularBuffer.h
	g++ -std=c++11 -ggdb3 -c circularBuffer.cpp -lpthread

clean:
	rm auxiliarry.o
